# Generated by Django 4.1.3 on 2023-06-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_dataset_schema_alter_schema_delimiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterOrderWithRespectTo(
            name='column',
            order_with_respect_to=None,
        ),
    ]
