# Generated by Django 4.1.3 on 2023-06-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_column_ordering_alter_column_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['schema', 'order'], 'verbose_name': 'Schema column', 'verbose_name_plural': 'Schema columns'},
        ),
        migrations.RenameField(
            model_name='column',
            old_name='ordering',
            new_name='order',
        ),
    ]
